repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ --maxkb=300 ]
      - id: check-merge-conflict

#  - repo: https://github.com/mobalt/markdownlint-cli
#    rev: v0.38.0
#    hooks:
#      - id: markdownlint-fix
